server:
 port: 8089

spring:
 application:
   name: APIGATEWAY

 cloud:
   kubernetes:
     discovery:
       enabled: true
       all-namespaces: true
       discovery-server-url: ${DISCOVERY-SERVER-URL}
     service:
       locator:
         enabled: true
   gateway:
     globalxcors:
       corsConfigurations:
         '[/**]':
           allowedOrigins: "**"
           allowedMethods:
             - GET
             - POST
             - DELETE
             - OPTIONS
             - PATCH
           allowedHeaders:
             - "*"
           allowCredentials: true

eureka:
  client:
    register-with-eureka: true  # Eureka 서버에 서비스 등록
    fetch-registry: true  # Eureka에서 다른 서비스 정보 조회
    service-url:
      defaultZone: http://<각자 ip>:8088/eureka  # Eureka 서버 주소

  instance:
    prefer-ip-address: true
    instance-id: APIGATEWAY:8089  # 고정 인스턴스 ID 설정
    lease-renewal-interval-in-seconds: 10  # 갱신 요청 간격 (초)
    lease-expiration-duration-in-seconds: 30  # 만료 시간 (초)

