server:
  port: 8089

spring:
  application:
    name: APIgateway



instance:
  lease-renewal-interval-in-seconds: 10  # 갱신 요청 간격 (초)
  lease-expiration-duration-in-seconds: 30  # 만료 시간 (초)

# eureka client 설정 추가
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.229:8088/eureka

